version: "3.8"
services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
